Medicio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('', include('main_page.urls', namespace='main_page')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation, contact_list, update_contact

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations_list'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reserve'),
    path('contact_form/', contact_list, name='contact_list'),
    path('contact_form/update/<int:pk>/', update_contact, name='update_contact'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user or not user.check_password(password):
                raise forms.ValidationError('Incorrect password or username')
            return super().clean()


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', )

    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean_password2(self, *args, **kwargs):
        data = self.cleaned_data
        if data['password'] == data['password2']:
            return data['password2']
        return forms.ValidationError('Passwords do not match')

manager/views.py
from django.shortcuts import render, redirect
from main_page.models import UserReservation, Contact
from django.contrib.auth.decorators import login_required, user_passes_test


def is_manager(user):
    return user.groups.filter(name='manager').exists()

@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservation_list(request):
    lst = UserReservation.objects.filter(is_processed=False)
    return render(request, 'reservation_list.html', context={'lst': lst})


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_reservation(request, pk):
    UserReservation.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservations_list')


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def contact_list(request):
    lst2 = Contact.objects.filter(is_processed=False)
    return render(request, 'contact_message.html', context={'lst2': lst2})


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_contact(request, pk):
    Contact.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:contact_list')

manager/templates/contact_message.html
{% extends 'index.html' %}
{% block content %}
    <section id="appointment">
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            {% for item in lst2 %}
                <div class="row">
                    <div class="col-md-3">
                        <a href='{% url "manager:update_contact" pk=item.pk %}'>
                            <button type="button" class="btn btn-primary">Close the application</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.subject }}</div>
                    <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                </div>
                <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-9"> {{ item.message }} </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </section>
{% endblock %}

manager/templates/log_in.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="section-title text-center">
            <h3>Log in</h3>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-6">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Log in">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

manager/templates/registration.html
{% extends 'index.html' %}
{% block content %}
    <div class="container">
        <div class="section-title text-center">
            <h3>Registration</h3>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-6">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Register">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

manager/templates/registration_done.html
{% extends 'index.html' %}

{% block content %}
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                <div class="col-md-6">
                    <h1 class="display-4">Hello, {{ new_user.username }}</h1>
                    <p>You have registered in the system</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}"

manager/templates/reservation_list.html
{% extends 'index.html' %}
{% block content %}
    <section id="appointment">
    <div class="container">
        <div class="col-md-10 col-md-offset-1">
            {% for item in lst %}
                <div class="row">
                    <div class="col-md-3">
                        <a href='{% url "manager:update_reserve" pk=item.pk %}'>
                            <button type="button" class="btn btn-primary">Close the application</button>
                        </a>
                    </div>
                    <div class="col-md-3">{{ item.name }}</div>
                    <div class="col-md-3">{{ item.phone }}</div>
                    <div class="col-md-3">{{ item.date|date:'d-m-Y' }}</div>
                </div>
                <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-9"> {{ item.message }} </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </section>
{% endblock %}