Medicio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import login_view, logout_view, registration_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', registration_view, name='registration'),
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('', include('main_page.urls', namespace='main_page')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation, contact_list, update_contact

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations_list'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reserve'),
    path('contact_form/', contact_list, name='contact_list'),
    path('contact_form/update/<int:pk>/', update_contact, name='update_contact'),
]

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Medicio Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png"%} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png"%} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/fontawesome-free/css/all.min.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/animate.css/animate.min.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/aos/aos.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/boxicons/css/boxicons.min.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css"%} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css"%} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/style.css"%} rel="stylesheet">

  <!-- =======================================================
  * Template Name: Medicio - v4.7.0
  * Template URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex align-items-center justify-content-center justify-content-md-between">
      <div class="align-items-center d-none d-md-flex">
        <i class="bi bi-clock"></i> Monday - Saturday, 8AM to 10PM
      </div>
      <div class="d-flex align-items-center">
        <i class="bi bi-phone"></i> Call us now +1 5589 55488 55
      </div>
    </div>
  </div>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <a href="index.html" class="logo me-auto"><img src={% static "assets/img/logo.png"%} alt=""></a>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <h1 class="logo me-auto"><a href="index.html">Medicio</a></h1> -->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto " href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto" href="#departments">Departments</a></li>
          <li><a class="nav-link scrollto" href="#doctors">Doctors</a></li>
          {% if 'manager' in user.groups.all.0.name %}
            <li class="dropdown"><a href="#"><span>Manager</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
{#              <li><a href="#">Drop Down 1</a></li>#}
{#              <li class="dropdown"><a href="#"><span>Manager</span> <i class="bi bi-chevron-right"></i></a>#}
{#                <ul>#}
{#                  <li><a href="{% url 'manager:reservations_list' %}">Appointments</a></li>#}
{#                  <li><a href="#">Deep Drop Down 2</a></li>#}
{#                  <li><a href="#">Deep Drop Down 3</a></li>#}
{#                  <li><a href="#">Deep Drop Down 4</a></li>#}
{#                  <li><a href="#">Deep Drop Down 5</a></li>#}
{#                </ul>#}
{#              </li>#}
              <li><a href="{% url 'manager:reservations_list' %}">Appointments</a></li>
              <li><a href="{% url 'manager:contact_list' %}">Contact Messages</a></li>
{#              <li><a href="#">Drop Down 4</a></li>#}
            </ul>
          </li>
          {% endif %}
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      <a href="#appointment" class="appointment-btn scrollto"><span class="d-none d-md-inline">Make an</span> Appointment</a>

    </div>
  </header><!-- End Header -->
  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div id="heroCarousel" data-bs-interval="5000" class="carousel slide carousel-fade" data-bs-ride="carousel">

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

      <div class="carousel-inner" role="listbox">

        <!-- Slide 1 -->
        <div class="carousel-item active" style="background-image: url({% static 'assets/img/slide/slide-1.jpg'%})">
          <div class="container">
            <h2>Welcome to <span>Medicio</span></h2>
            <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel.</p>
            <a href="#about" class="btn-get-started scrollto">Read More</a>
          </div>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item" style="background-image: url({% static 'assets/img/slide/slide-2.jpg'%})">
          <div class="container">
            <h2>Lorem Ipsum Dolor</h2>
            <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel.</p>
            <a href="#about" class="btn-get-started scrollto">Read More</a>
          </div>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item" style="background-image: url({% static 'assets/img/slide/slide-3.jpg'%})">
          <div class="container">
            <h2>Sequi ea ut et est quaerat</h2>
            <p>Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel.</p>
            <a href="#about" class="btn-get-started scrollto">Read More</a>
          </div>
        </div>

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon bi bi-chevron-left" aria-hidden="true"></span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon bi bi-chevron-right" aria-hidden="true"></span>
      </a>

    </div>
  </section><!-- End Hero -->


    {% block content %}
    {% endblock %}

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/purecounter/purecounter.js"%}></script>
  <script src={% static "assets/vendor/aos/aos.js"%}></script>
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js"%}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js"%}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js"%}></script>
  <script src={% static "assets/vendor/php-email-form/validate.js"%}></script>

  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js"%}></script>

</body>

</html>